/*
   -- 001_robot_lite_app_v1.0 --
   
   To compile this code using RemoteXY library 3.1.13 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.15.01 or later version;
     - for iOS 1.12.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.    
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLE

#include <BLEDevice.h>

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "01_ble"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 176 bytes
  { 255,3,0,15,0,169,0,19,0,0,0,0,179,2,130,200,108,200,1,1,
  5,0,5,32,128,71,71,23,109,60,60,21,137,178,179,68,1,52,128,62,
  3,41,33,40,51,180,50,133,94,68,105,115,116,97,110,99,101,0,83,112,
  101,101,100,0,66,97,116,116,101,114,121,0,72,66,22,37,37,2,3,24,
  24,108,166,140,178,180,0,0,0,0,0,0,200,66,0,0,0,0,137,0,
  0,0,0,0,0,240,65,79,0,0,248,65,0,0,112,66,50,0,0,116,
  66,0,0,200,66,1,1,1,128,20,40,253,24,24,9,179,31,119,111,114,
  107,115,104,111,112,45,100,105,121,46,111,114,103,32,58,32,65,80,80,95,
  86,49,46,48,0,69,17,27,19,19,2,175,20,20,0,150 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  int8_t joystick_01_x; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100
  uint8_t button_01; // =1 if button pressed, else =0

    // output variables
  float onlineGraph_01_distance;
  float onlineGraph_02_speed;
  float onlineGraph_03_battery;
  int8_t circularBar_01; // from 0 to 100
  int16_t sound_01; // =0 no sound, else ID of sound, =1001 for example, look sound list in app

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////



void setup() 
{
  RemoteXY_Init (); 
  
  
  // TODO you setup code
  
}

void loop() 
{ 
  RemoteXY_Handler ();
  
  
  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXY_delay() 


}